### ISSUE TITLE
Remove UserVoice, replace with GitHub issues

### ISSUE THREAD

**Issue by jrummell** [jrummell/facebooksteamachievements#20]

**Comment by romansp** [comment]
Hi. Found this issue via 'hacktoberfest' label. Can you elaborate a little more what do you expect from a PR fixing this one?

**Comment by jrummell** [comment]
@romansp Since the UserVoice markup is handled by a config setting, it would be as simple as renaming anything in the code named with UserVoice to something more generic, like IssueTracker.

**Comment by romansp** [comment]
Thanks 👍. Got it.
