### ISSUE TITLE
Achievement info not displaying

### ISSUE THREAD

**Issue by godofrock456** [jrummell/facebooksteamachievements#27]
When sharing achievements it isn't showing anything, it just says no information. It was working fine yesterday.

![steam achievement error](https://user-images.githubusercontent.com/30278944/28348286-1b2213bc-6c34-11e7-9956-c16598ca2ada.png)

**Comment by jrummell** [comment]
According to https://developers.facebook.com/docs/sharing/reference/feed-dialog#deprecated-params, images and captions are now ignored in the feed dialog. 

The share dialog still allows a caption https://developers.facebook.com/docs/sharing/reference/share-dialog#params

**Comment by jrummell** [comment]
This will be fixed with #30
